version: '3.5'
    
services:
  postgres:
    #build:
    #  dockerfile: Dockerfile
    #  context: .
    container_name: postgres
    hostname: postgres
    image: postgres:16.2
    environment:
      ENV: postgres.env
    env_file:
      - ./postgres.env
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=256MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_directory=/logs"
      - "-c"
      - "logging_collector=on"
      - "-c"
      # logging with day name prefix, example: postgresql_Sun.log
      - "log_filename=postgresql_%a.log"
      - "-c"
      - "log_truncate_on_rotation=on"
      - "-c"
      - "log_rotation_age=1d"
      - "-c"
      - "log_min_duration_statement=1500"
      - "-c"
      - "log_checkpoints=on"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "log_disconnections=on"
      - "-c"
      - "log_line_prefix=%t [%p]: [%l-1] user=%u,db=%d"
      - "-c"
      - "log_lock_waits=on"
      - "-c"
      - "log_temp_files=0"
      - "-c"
      - "statement_timeout=1800000"
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      PGDATA: /data/postgres
    volumes:
      #- ./services/postgres_data:/data/postgres
      - ./logs:/logs
      - ./data/postgres:/data/postgres
      - ./pg_dump:/data/pg_dump
      - ./cron/pgsql_backup.sh:/etc/cron.daily/pgsql_backup.sh
      - ./cron/postgres.env:/etc/postgres.env
    ports:
      - "5432:5432"
    expose:
      - 5432
    #networks:
    #  - postgres
    restart: unless-stopped

